export let resList = [
  {
    id: "5624",
    name: "Subway",
    cloudinaryImageId: "63178e3e64d503a479f2a2048a474552",
    locality: "BHAMBURDA",
    areaName: "MOSIAK COMMERCIAL COMPLEX",
    costForTwo: "₹350 for two",
    cuisines: ["Healthy Food", "Salads", "Snacks", "Desserts", "Beverages"],
    avgRating: 3.3,
    parentId: "2",
    avgRatingString: "4.3",
    totalRatingsString: "10K+",
    slaString: "45-50 mins",
    lastMileTravelString: "2.1 km",
  },
  {
    id: "20058",
    name: "SP's Biryani House",
    cloudinaryImageId: "b2jeywla2n5b8h25ey1p",
    locality: "Sadashiv Peth",
    areaName: "Sadashiv Peth",
    costForTwo: "₹900 for two",
    cuisines: ["Biryani", "North Indian", "Indian", "Maharashtrian"],
    avgRating: 4.4,
    parentId: "192891",
    avgRatingString: "4.4",
    totalRatingsString: "10K+",
    slaString: "30-35 mins",
    lastMileTravelString: "1.8 km",
  },
  {
    id: "362543",
    name: "Fish Curry Rice",
    cloudinaryImageId: "bwsforithqwchih1s3b3",
    locality: "Tilak Road",
    areaName: "Sadashiv Peth",
    costForTwo: "₹1000 for two",
    cuisines: ["Indian"],
    avgRating: 3.5,
    parentId: "374",
    avgRatingString: "4.5",
    totalRatingsString: "500+",
    slaString: "30-35 mins",
    lastMileTravelString: "1.9 km",
  },
  {
    id: "32443",
    name: "Natural Ice Cream",
    cloudinaryImageId: "p8af4xnqjzsei0umtgnn",
    locality: "JM Road",
    areaName: "Shivajinagar",
    costForTwo: "₹150 for two",
    cuisines: ["Ice Cream", "Desserts"],
    avgRating: 4.8,
    veg: true,
    parentId: "2093",
    avgRatingString: "4.8",
    totalRatingsString: "5K+",
    slaString: "20-25 mins",
    lastMileTravelString: "1.2 km",
  },
  {
    id: "11887",
    name: "Samudra Veg",
    cloudinaryImageId: "b7r9runu5yjkfsl20tri",
    locality: "Pandurang Colony",
    areaName: "Erandwane",
    costForTwo: "₹450 for two",
    cuisines: ["North Indian", "Chinese", "South Indian"],
    avgRating: 3.9,
    veg: true,
    parentId: "176775",
    avgRatingString: "4.5",
    totalRatingsString: "10K+",
    slaString: "30-35 mins",
    lastMileTravelString: "3.6 km",
  },
  {
    id: "20154",
    name: "Nisarg",
    cloudinaryImageId: "kqldoyhvqgq48g5iuqgn",
    locality: "Erandwane",
    areaName: "Erandwane",
    costForTwo: "₹1200 for two",
    cuisines: ["Coastal"],
    avgRating: 2.4,
    parentId: "149328",
    avgRatingString: "4.4",
    totalRatingsString: "5K+",
    slaString: "35-40 mins",
    lastMileTravelString: "3.7 km",
  },
  {
    id: "29639",
    name: "Eatsome- Wraps & Rolls",
    cloudinaryImageId: "e56240a4b58956f47a5a1f8392470fbe",
    locality: "J.M.Road",
    areaName: "Shivajinagar",
    costForTwo: "₹300 for two",
    cuisines: ["North Indian", "Biryani", "Street Food", "Beverages"],
    avgRating: 4.2,
    parentId: "471587",
    avgRatingString: "4.2",
    totalRatingsString: "5K+",
    slaString: "30-35 mins",
    lastMileTravelString: "1.7 km",
  },
  {
    id: "5743",
    name: "Madinah",
    cloudinaryImageId: "n07bhbglbqthyd45clul",
    locality: "Camp",
    areaName: "Camp",
    costForTwo: "₹350 for two",
    cuisines: ["Mughlai", "North Indian", "Chinese", "Biryani"],
    avgRating: 3.9,
    parentId: "1397",
    avgRatingString: "3.9",
    totalRatingsString: "10K+",
    slaString: "30-35 mins",
    lastMileTravelString: "3.0 km",
  },
  {
    id: "394784",
    name: "Theobroma",
    cloudinaryImageId: "b033728dcb0101ceb19bff0e1e1f6474",
    locality: "Shivaji Nagar",
    areaName: "Shivajinagar",
    costForTwo: "₹400 for two",
    cuisines: ["Bakery", "Desserts"],
    avgRating: 4.6,
    parentId: "1040",
    avgRatingString: "4.6",
    totalRatingsString: "1K+",
    slaString: "25-30 mins",
    lastMileTravelString: "1.8 km",
  },
];
